version: '3'

services:
  search_api:
    container_name: 'search_api'
    build: .
    restart: 'on-failure'
    volumes:
      - ${PWD}/search-api:/app
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.2'
    ports:
      - '9200:9200'

